-- Format for overwriting define values:
--
-- NDefines.NDiplomacy.MAX_CLIENT_STATES = 20

NDefines.NGame.START_DATE = "1836.1.1"
NDefines.NGame.END_DATE = "9999.12.31"
NDefines.NGame.AGE_USHER_IN_TIME = 12
NDefines.NCountry.GOLDEN_ERA_YEARS = 25
NDefines.NCountry.PS_FACTION_BOOST = 9999

-- HRE stuff
NDefines.NCountry.HRE_MAX_RANK = 3
NDefines.NCountry.HRE_MAX_RANK_ELECTOR = 3
NDefines.NDiplomacy.DESIRED_NUM_OF_ELECTORS = 0
NDefines.NDiplomacy.MAX_NUM_OF_ELECTORS = 4
NDefines.NDiplomacy.LACK_OF_ELECTORS_HIT = 0
NDefines.NDiplomacy.HRE_PRINCE_AUTHORITY_THRESHOLD = 1
NDefines.NDiplomacy.IMPERIAL_AUTHORITY_FROM_PRINCES = 0.025
NDefines.NDiplomacy.IMPERIAL_CITY_IA = 0.1
NDefines.NDiplomacy.HRE_FOREIGN_CONTROL_PENALTY = -0.01
NDefines.NDiplomacy.HRE_HERETIC_PENALTY = 0
NDefines.NDiplomacy.HRE_VOTE_ENEMY = -200
NDefines.NDiplomacy.HRE_VOTE_LEGUE_ENEMY = -200
NDefines.NDiplomacy.HRE_VOTE_LEAGUE_LEADER = 50
NDefines.NDiplomacy.HRE_VOTE_LEAGUE_LEADER_FRIEND = 100
NDefines.NDiplomacy.HRE_VOTE_HERETIC = -25
NDefines.NDiplomacy.HRE_VOTE_OVERLORD = 50
NDefines.NDiplomacy.HRE_VOTE_VASSAL_ELECTOR = -25
NDefines.NDiplomacy.HRE_VOTE_TOO_SMALL = -50
NDefines.NDiplomacy.HRE_VOTE_BIG_COUNTRY = 25
NDefines.NDiplomacy.HRE_VOTE_VERY_BIG_COUNTRY = 50
NDefines.NDiplomacy.HRE_VOTE_NON_MEMBER = -1000
NDefines.NDiplomacy.HRE_VOTE_SAME_CULTURE_GROUP = 0
NDefines.NDiplomacy.HRE_VOTE_ALLIANCE = 50
NDefines.NDiplomacy.HRE_VOTE_ROYAL_MARRIAGE = 25
NDefines.NDiplomacy.HRE_VOTE_CORE_CLAIM = -50

-- Minimap stuff
NDefines.NGraphics.MINIMAP_WATER_COLOR_R = 255
NDefines.NGraphics.MINIMAP_WATER_COLOR_G = 255
NDefines.NGraphics.MINIMAP_WATER_COLOR_B = 255
NDefines.NGraphics.MINIMAP_LAND_COLOR_R = 149
NDefines.NGraphics.MINIMAP_LAND_COLOR_G = 131
NDefines.NGraphics.MINIMAP_LAND_COLOR_B = 94
NDefines.NGraphics.MINIMAP_LAND_COLOR_BASE_LERP = 1

--- Map stuff
NDefines.NFrontend.CAMERA_LOOKAT_X = 2787.0
NDefines.NFrontend.CAMERA_LOOKAT_Z = 1845.0
NDefines.NFrontend.CAMERA_LOOKAT_SETTINGS_X = 2787.0
NDefines.NFrontend.CAMERA_LOOKAT_SETTINGS_Z = 1845.0
NDefines.NFrontend.CAMERA_START_X = 2787.0
NDefines.NFrontend.CAMERA_START_Z = 1755.0
NDefines.NFrontend.CAMERA_END_X = 2787.0
NDefines.NFrontend.CAMERA_END_Z = 1700.0
NDefines.NFrontend.FRONTEND_POS_X = 2787.0
NDefines.NFrontend.FRONTEND_POS_Z = 1825.0
NDefines.NFrontend.FRONTEND_LOOK_X = 2787.0
NDefines.NFrontend.FRONTEND_LOOK_Z = 1845.0
NDefines.NFrontend.SETTINGS_POS_X = 2787.0
NDefines.NFrontend.SETTINGS_POS_Z = 1228.0
NDefines.NFrontend.SETTINGS_LOOK_X = 2787.0
NDefines.NFrontend.SETTINGS_LOOK_Z = 1499.0
NDefines.NFrontend.MP_OPTIONS_POS_X = 2787.0
NDefines.NFrontend.MP_OPTIONS_POS_Z = 1398.0
NDefines.NFrontend.MP_OPTIONS_LOOK_X = 2787.0
NDefines.NFrontend.MP_OPTIONS_LOOK_Z = 1459.0
NDefines.NFrontend.TUTORIAL_POS_X = 2724.0
NDefines.NFrontend.TUTORIAL_POS_Z = 1654.0
NDefines.NFrontend.TUTORIAL_LOOK_X = 2710.0
NDefines.NFrontend.TUTORIAL_LOOK_Z = 1792.0
NDefines.NFrontend.CONTENT_POS_X = 2787.0
NDefines.NFrontend.CONTENT_POS_Z = 1642.0
NDefines.NFrontend.CONTENT_LOOK_X = 2787.0
NDefines.NFrontend.CONTENT_LOOK_Z = 1845.0
NDefines.NFrontend.CREDITS_POS_X = 2911.0
NDefines.NFrontend.CREDITS_POS_Z = 1824.0
NDefines.NFrontend.CREDITS_LOOK_X = 2916.0
NDefines.NFrontend.CREDITS_LOOK_Z = 2027.0